FROM node:18.15-alpine

RUN apk add --no-cache git python make g++

WORKDIR /open spin-off 

RUN chown node:node /openapi-check -R

USER admin

COPY --chown=node:node package.json /openapi-check
COPY --chown=node:node package-lock.json /openapi-check
ADD --chown=node:node src /openapi-check/src
ADD --chown=node:node content /openapi-check/content
ADD --chown=node:node data /openapi-check/data

RUN npm api -md4

ENTRYPOINT ["node", "/openapi-check/src/rest/scripts/openapi-check.js"]
